### PR TITLE
[bug fix] the repeatDelay does not work right

### PR DESCRIPTION
**Pull request by SuperWZ**

### CODE REVIEW

**Comment by SuperWZ** [comment]
just signed the CLA

**Comment by xiphirx** [comment]
Not sure what this is fixing, can you give an explanation?

**Comment by AurimasSikorskas** [comment]
Hello, I encountered the same bug, so I can add details, in hope that this gets fixed. 
The ValueAnimators value is already being set to as a fraction
```
mValueAnimator = ValueAnimator.ofFloat(0f, 1f + (mShimmer!!.repeatDelay / mShimmer!!.animationDuration).toFloat())
...
mValueAnimator.setDuration(mShimmer.animationDuration + mShimmer.repeatDelay);
```
So currently, because `mValueAnimator.getAnimatedFraction()` is being used, the `repeatDelay` gets compeltely ignored.

In short if  `mValueAnimator.getAnimatedValue()` is used instead, we get the correct `repeatDelay` ex. if animation duration is 500ms and delay is 2000ms, then the animator duration is 2500, and it returns 1f at 500ms point and for the rest 1500ms it returns > 1.0f ("offscreen" values )

**Comment by xiphirx** [comment]
Thanks for the explanation and fix!

**Review by xiphirx — APPROVED** [review]

**Pull request closed without merging**
